### PR TITLE
Reflect the changes in the dashboard service's api documentation and Fix bug

### PR DESCRIPTION
**Pull request by stat-kwon**
### Category
- [ ] New feature
- [x] Bug fix
- [x] Improvement
- [x] Refactor
- [ ] etc

### Description
- Overall, we have reflected the changes in the dashboard service's api documentation.
    
    - Fixed user_id related logic and error message.
    - Fixed minimal field in domain dashboard and project dashboard
    - Updated test code according to changes.

### Known issue
* #1

### CODE REVIEW

**Comment by stat-kwon** [comment]
We changed the terminology because widget_id is ambiguous from the point of view of api users.

AS-IS
`widget_id`
`name`

TO-BE
`widget_name`
`title`

Custom dashboard related model, manager, service, etc. have been changed.
Code review please. @whdalsrnt @jihyungSong

**Comment by stat-kwon** [comment]
I set `enabled=false` in the model's settings in the domain and project dashboard.

As a result of the test code, the sub-option of setting has false by default as shown in the figure below.

```python
{   '_id': ObjectId('6368917388b936d48339a54e'),
    'created_at': datetime.datetime(2022, 11, 7, 5, 2, 43, 179772),
    'dashboard_options': {'project_id': 'project-1234'},
    'dashboard_options_schema': {},
    'domain_dashboard_id': 'domain-dash-6cbd4544c1ab',
    'domain_id': 'domain-12345',
    'labels': [],
    'layouts': [],
    'name': 'test',
    'scope': 'USER',
    'settings': {   'currency': SON([('enabled', False)]),
                    'date_range': SON([('enabled', False)])},
    'tags': {},
    'updated_at': datetime.datetime(2022, 11, 7, 5, 2, 43, 179774),
    'user_id': 'cloudforet@gmail.com'}
```

**Review by jihyungSong — APPROVED** [review]
In general, only the code convention were checked. 
The PR codes is too big to see the full logic.

**Review by whdalsrnt — APPROVED** [review]
The first commit is too large for a full view.
Let's improve the code after merging.

**Pull request merged**
